### ISSUE TITLE
Faster download of RKI data

### ISSUE THREAD

**Issue by joaopn** [Priesemann-Group/covid19_inference#12]
Since we always use the full RKI dataset, it is faster to download the data one-shot instead of by Landkreise. The RKI now offers that: https://www.arcgis.com/sharing/rest/content/items/f10774f1c63e40168479a1feb6c7ca74/data

This fixes an issue:
* REST api can sometimes not return the full dataset (updating?), which is why we current check if #landkreise < 412

But creates another:
* Fields in the csv can be inconsistent, column names so far were sometimes e.g. "AnzahlFall" and other times "Anzahl Fall". Datestand also follows a different  "19.04.2020, 00:00 Uhr" format, but we don't use that.

We could use first try the csv, then fall back to the api if it fails.

**Comment by jdehning** [comment]
Seems a good proposal to me
