### ISSUE TITLE
Add black formatter

### ISSUE THREAD

**Issue by jdehning** [Priesemann-Group/covid19_inference#18]
Add a pre-commit hook to format submitted code with black

**Comment by pSpitzner** [comment]
I suggest we tackle this along with Travis CI. Automated testing feels more urgent, anyway.

**Comment by pSpitzner** [comment]
So travis works as of 62bffca5b9eddc1c60546a97cce9dd0899094d20. I decided against adding black formatting into the travis test, for now.

Instead, anyone who wants to push to the repo can setup black as a pre-commit hook locally (as suggested by the black developers). The required `.pre-commit-hook` is now in the repo.

```
conda install -c conda-forge pre-commit
pre-commit install
```

and thereafter, black should automatically run on the python files that are part of the commit.
