### ISSUE TITLE
Problems with RKI data retrieval 

### ISSUE THREAD

**Issue by jdehning** [Priesemann-Group/covid19_inference#21]
The example notebooks are not working because there is some problem with the datetime object. I pushed the failing notebooks including the error message
@semohr Could you look at it?

**Comment by semohr** [comment]
`df_bundeslaender = rki.filter_all_bundesland('2020-03-10', '2020-04-19')` expects two datetime objects as arguments. It was intended like that see #8 and readthedocs. I forgot to add this to the example_bundeslaender sheet, easy fixed like this:
`begin_date = datetime.datetime(2020,3,10)`
`end_date = datetime.datetime(2020,4,19)`
`df_bundeslaender = rki.filter_all_bundesland(begin_date, end_date )`

**Comment by jdehning** [comment]
Yep, this I already fixed. It is something else...

**Comment by semohr** [comment]
Ah in the other notebook 
`bd = datetime.datetime.strptime("2020,03-10",'%y %m %d')`
`ed = datetime.datetime.strptime("2020-04-13",'%y %m %d')`
this is not working for obvious reasons. Do you mean that?
Fix is to add change '%y %m %d' to '%y-%m-%d' or create the objects like this:
`bd = datetime.datetime.strptime(2020,3,10)`
`ed = datetime.datetime.strptime(2020,4,13)`

**Comment by semohr** [comment]
I see... even more errors well I will look into it more :+1:

**Comment by jdehning** [comment]
Yes, I forgot to push the notebooks. Then you would have seen the errors straigtht away
