### ISSUE TITLE
Import error when module covid19_inference is installed (instead of loaded from directory)

### ISSUE THREAD

**Issue by mgirardis** [Priesemann-Group/covid19_inference#42]
1) I installed covid19_inference from pip as advised in the docs
All ran successfully (Windows 10, Python 3.8.2)

2) Initialize python and type
`import covid19_inference`

getting the error:
 > Traceback (most recent call last):
 >   File "<stdin>", line 1, in <module>
 >   File "C:\Users\girar\AppData\Roaming\Python\Python38\site-packages\covid19_inference\__init__.py", line 11, in <module>
 >     from . import data_retrieval
 > ImportError: cannot import name 'data_retrieval' from partially initialized module 'covid19_inference' (most likely due to a circular import) (C:\Users\girar\AppData\Roaming\Python\Python38\site-packages\covid19_inference\__init__.py)

3) If I uninstall covid19_inference and import covid19_inference from the directory, the error does not happen

4) This error happens when running 1st cell in example_bundeslaender.ipynb with covid19_inference installed, but it does not happen when covid19_inference is not installed.

**Comment by jdehning** [comment]
@semohr If you have time could you have a look?
