### ISSUE TITLE
Region population size

### ISSUE THREAD

**Issue by truEngineer** [Priesemann-Group/covid19_inference#44]
In the [example](https://github.com/Priesemann-Group/covid19_inference/blob/master/scripts/example_one_bundesland.ipynb) for one region (Sachsen), the population of all of Germany is used `N_population = 83e6`. Is this parameter important in the model, taking into account the forecasts obtained in this example?

**Comment by jdehning** [comment]
This shouldn't be the case, but it doesn't make a difference in the results, as the case numbers are well below the 'herd immunity'

**Comment by semohr** [comment]
Fixed in bc6e0e1. Not merged yet though.

**Comment by semohr** [comment]
Merged into master b39a992ec974c1952aaab8175660c3031e4e8824
