### ISSUE TITLE
Script for simple SIR and SEIR models

### ISSUE THREAD

**Issue by chrisborges** [Priesemann-Group/covid19_inference#46]
The script for the full SIR model runs perfectly. However, I am having a hard time implementing the simple SIR model and the SEIR model. Could you upload a script for those models?

**Comment by jdehning** [comment]
They are in the other repository: https://github.com/Priesemann-Group/covid19_inference_forecast
In the readme there, the folder with the scripts is referenced.

**Comment by chrisborges** [comment]
Thank you for replying. I am aware of the other repository. But since that module is no longer being developed, those codes are outdated and a little tricky to adapt. I will keep soldiering on. Congratulations on your work, btw.
