### ISSUE TITLE
doubt about the posterior distributions

### ISSUE THREAD

**Issue by Quan-kas** [Priesemann-Group/covid19_inference#56]
Hello good morning, I am writing a report of your model which is great, but I have a question about the posterior distributions of the parameters, is it the same as the a priori? Is there a way to know exactly the posterior distributions? Would it be helpful to me, please in which part of the model code do you multiply the a priori distribution with the maximum likelihood function?

I appreciate your help

**Comment by jdehning** [comment]
The posterior is not the same as the prior. The posterior is calculated with pm.sample(...). The prior is multiplied with the likelihood internally in the PyMC3 package

**Comment by Quan-kas** [comment]
perfect thank you very much, I will investigate the pymc3 package and see the pm.sample function,

Thank you
